### ISSUE TITLE
Detect and Resolve Parallel Simulation Freeze

### ISSUE THREAD

**Issue by NazirNayal8** [yhassanzadeh13/lightchain-container#1]
# Context

When running a simulation of a number of nodes (above some certain number with some specific parameters) where nodes run in parallel each in a separate thread, the system suddenly freezes and nodes stop responding. We have postulated to possible reasons for this problem so far:
* While requests are going on between threads (nodes), some nodes are waiting for results from some other threads in such a way that it creates a circular dependency and a circular deadlock. We suspect that if this is the case, it happens at requests related to node insertions, because the lookup table of the skip graph implements locks to protect the info from concurrent reads and writes.
* We have used a software called Java VisualVM to track the status of the threads at the point where the deadlocks happens. The Analyzer which is supposed to detect and locate the deadlocks did not spot any. Instead it reported the following:
   * 62% of all threads are waiting for a monitor without a application thread holding it. This indicates a congestion. It is very likely the garbage collector is running and is blocking the monitors
   * And, it also pointed out that most of the threads are waiting for a single monitor, which is acquired by a single thread, which does not seem like a deadlock as in a circular thread dependency for example, but there might be another reason why the threads are blocking. Perhaps retrying with the program and making further analysis would make the problem clearer.

# Task

The task is to recreate the simulation issue using several parameters, identifying the cause, and solving it.

# Definition of Done

To work the changes on a separate branch and open a pull request after finishing the task.

**Comment by thep2p** [comment]
Great @NazirNayal8 thanks for elaborating on this.

**Comment by thep2p** [comment]
@sarieh as @NazirNayal8 describes, I also agree that starting with the garbage collector is a very good clue:
> 62% of all threads are waiting for a monitor without a application thread holding it. This indicates a congestion. It is very likely the garbage collector is running and is blocking the monitors
